export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

export const COMICS_REQUEST = 'COMICS_REQUEST';
export const COMICS_SUCCESS = 'COMICS_SUCCESS';
export const COMICS_FAILURE = 'COMICS_FAILURE';

export const COMIC_REQUEST = 'COMIC_REQUEST';
export const COMIC_SUCCESS = 'COMIC_SUCCESS';
export const COMIC_FAILURE = 'COMIC_FAILURE';

export const CHAPTERS_REQUEST = 'CHAPTERS_REQUEST';
export const CHAPTERS_SUCCESS = 'CHAPTERS_SUCCESS';
export const CHAPTERS_FAILURE = 'CHAPTERS_FAILURE';

export const COMIC_SET = 'COMIC_SET';
